version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: alb-crm-postgres
    environment:
      POSTGRES_DB: alb_crm
      POSTGRES_USER: alb
      POSTGRES_PASSWORD: alb_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: alb-crm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alb.local
      PGADMIN_DEFAULT_PASSWORD: Password123!
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
